Repository modern-agile-team/ModernWorld-Front, pull requests merged in 2024-06, with the labels that each got.

#26 bug(#14): 데이터 불러오기 수정
  .vscode/settings.json
  src/app/api/GetItems.tsx
  src/app/api/getUserItem.ts
  src/app/api/mock.ts
  src/app/test/page.tsx
  src/components/my-page/contents/inventory/InvenRightBookMark.tsx
  src/components/my-page/contents/inventory/InventoryItemBox.tsx
  src/components/my-page/contents/inventory/style.ts
  src/components/my-page/contents/style.ts
  src/hooks/GetInventoryList.tsx
  src/page.tsx
  src/state/itemAtoms.ts
  src/utils/useGetData.ts
Labels: Bug fix, Feature

#25 feature&publish(#22):그리드 나누기하고 이미지 불러오기
  src/app/api/GetItems.tsx
  src/app/test/page.tsx
  src/components/my-room/MyRoom.tsx
  src/components/my-room/style.ts
Labels: Publish, Feature

#28 인벤토리 수정 프로필 데이터 불러오기 진행하겠습니다~
  src/app/api/getUser.ts
  src/components/my-page/contents/inventory/InventoryItemBox.tsx
  src/components/my-page/contents/inventory/style.ts
  src/components/shop-page/ShopRightBookMark.tsx
  src/hooks/PageNumber.ts
  src/hooks/useSearchBar.ts
  src/state/userAtoms.ts
Labels: Modify, Feature
