Repository modern-agile-team/ModernWorld-Front, pull requests merged in 2024-07, with the labels that each got.

#55 setting(#49):types 폴더 생성 후 style.d. 파일에 인벤토리, 선물함 컴포넌트 타입선언
  src/components/my-page/contents/inventory/style.ts
  src/components/my-page/contents/mail-box/style.ts
  src/components/my-page/contents/style.ts
  src/components/my-page/pagination/style.ts
  src/components/my-page/user/style.ts
  src/types/style.d.ts
Labels: ⚙ Setting

#56 modify(#14) : 인벤토리 아이템 데이터 jotai 대신 useState 사용
  src/components/my-page/contents/inventory/InventoryItemBox.tsx
  src/states/itemAtoms.ts
Labels: 📝 Modify

#57 feature(#14):인벤토리 상위 라벨 구현 및 캐릭터 착용 기능 구현
  src/app/api/inventory.ts
  src/components/my-page/contents/inventory/InvenRightBookMark.tsx
  src/components/my-page/contents/inventory/InventoryHeader.tsx
  src/components/my-page/contents/inventory/InventoryItemBox.tsx
  src/components/my-page/user/LeftSection.tsx
  src/states/inventoryAtoms.ts
  src/states/itemAtoms.ts
  src/states/userAtoms.ts
Labels: ✨ Feature

#60 setting(#49):user 데이터 불러오는 atom 타입 파일 적용완료
  src/components/my-page/user/CharacterInfo.tsx
  src/components/my-page/user/LeftSection.tsx
  src/components/my-page/user/PointInfo.tsx
  src/states/userAtoms.ts
  src/types/user.d.ts
Labels: ⚙ Setting

#61 feature(#45):선물함 api 생성
  src/app/api/mailBox.ts
  src/components/my-page/contents/mail-box/GiftTitle.tsx
  src/components/my-page/contents/mail-box/ItemList.tsx
  src/components/my-page/contents/mail-box/ItemListEle.tsx
  src/components/my-page/contents/mail-box/MailBox.tsx
  src/components/my-page/contents/mail-box/MailBoxBody.tsx
  src/components/my-page/contents/mail-box/MailBoxBodyEle.tsx
  src/components/my-page/contents/mail-box/SideBookMark.tsx
  src/states/mailboxAtoms.ts
Labels: ✨ Feature

#64 feature(#45) : 선물 리스트로 불러올 수 있는 데이터 전부 불러옴 + 새로운 api 추가 전 커밋
  src/app/api/mailBox.ts
  src/components/my-page/contents/mail-box/GiftTitle.tsx
  src/components/my-page/contents/mail-box/ItemInfo.tsx
  src/components/my-page/contents/mail-box/MailBoxBodyEle.tsx
  src/hooks/test
  src/states/mailboxAtoms.ts
Labels: ✨ Feature

#65 feature(#45): 메일함 데이터 불러오기 완료 (리팩토링 필요함)
  src/components/my-page/contents/mail-box/GiftTitle.tsx
  src/components/my-page/contents/mail-box/ItemInfo.tsx
  src/components/my-page/contents/mail-box/ItemList.tsx
  src/components/my-page/contents/mail-box/MailBoxBodyEle.tsx
  src/components/my-page/pagination/Pagination.tsx
  src/states/mailboxAtoms.ts
  src/types/mailBox.d.ts
Labels: ✨ Feature

#63 publish(#62):grid 쪼개는 중입니다
  src/app/api/inventory.ts
  src/app/api/village.ts
  src/app/test/page.tsx
  src/components/index-page/LoginPage.tsx
  src/components/index-page/MainPage.tsx
  src/components/index-page/NewCharacter.tsx
  src/components/my-page/user/LeftSection.tsx
  src/components/my-room/Area1_4_5.tsx
  src/components/my-room/Area6_7_8.tsx
  src/components/my-room/GetUserCharacter.tsx
  src/components/my-room/MyRoom.tsx
  src/components/my-room/style.ts
  src/components/my-room/useCheckAreaHook.ts
  src/components/village-page/SearchBox.tsx
  src/components/village-page/getUserApi.tsx
  src/page.tsx
  src/types/inventory.d.ts
  src/types/myroom.d.ts
  src/types/style.d.ts
  src/types/village.d.ts
Labels: ✨ Feature, 🎨 Publish

#66 feat(#45):수락하기/거절하기 UI 만 만들어둔 상태 (기능 추가 필요)
  src/app/api/mailBox.ts
  src/components/my-page/contents/mail-box/ItemInfo.tsx
  src/components/my-page/contents/mail-box/MailBoxBody.tsx
  src/components/my-page/contents/mail-box/style.ts
  src/components/my-page/pagination/Pagination.tsx
  src/states/mailboxAtoms.ts
Labels: ✨ Feature, 🎨 Publish

#70 feature(#45) : 수정된 api url 변경 및 mailBox atom 변경 + 기능 추가 중
  src/app/api/inventory.ts
  src/app/api/mailBox.ts
  src/components/my-page/contents/mail-box/GiftTitle.tsx
  src/components/my-page/contents/mail-box/ItemInfo.tsx
  src/components/my-page/contents/mail-box/ItemList.tsx
  src/components/my-page/contents/mail-box/ItemListEle.tsx
  src/components/my-page/contents/mail-box/MailBox.tsx
  src/components/my-page/contents/mail-box/MailBoxBody.tsx
  src/components/my-page/contents/mail-box/MailBoxBodyEle.tsx
  src/components/my-page/contents/mail-box/PostInfo.tsx
  src/components/my-page/contents/mail-box/PresentInfo.tsx
  src/components/my-page/contents/mail-box/SideBookMark.tsx
  src/components/my-page/contents/mail-box/style.ts
  src/components/my-page/pagination/Pagination.tsx
  src/states/mailboxAtoms.ts
  src/types/mailBox.d.ts
  src/types/style.d.ts
Labels: 📝 Modify

#75 setting/#67: dockerfile, docker-compose, dockerignore 작성
  .dockerignore
  docker-compose.yml
  dockerfile
Labels: ⚙ Setting

#84 feat(#83):상점 아이템 클릭시 모달창 띄우기
  src/app/api/shop.ts
  src/components/my-page/contents/inventory/style.ts
  src/components/shop-page/ItemClick.tsx
  src/components/shop-page/ShopItemBox.tsx
  src/states/shopAtoms.ts
Labels: ✨ Feature, 🎨 Publish

#85 feat(#81):선물하기 기능 추가
  src/app/api/shop.ts
  src/components/my-page/contents/inventory/style.ts
  src/components/shop-page/GiftPage.tsx
  src/components/shop-page/ItemClick.tsx
  src/states/shopAtoms.ts
Labels: ✨ Feature

#89 bugfix : 브랜치 변경 전 오류 수정
  src/app/api/inventory.ts
  src/components/my-page/contents/inventory/InventoryItemBox.tsx
  src/components/my-page/contents/my-page-index/MyPage.tsx
  src/components/my-page/contents/my-page-index/style.ts
  src/components/my-page/user/CharacterInfo.tsx
  src/components/my-page/user/LeftSection.tsx
  src/states/mailboxAtoms.ts
  src/types/inventory.d.ts
Labels: 🐞 BugFix

#91 Setting/프론트 서버와 cicd 구현/#67
  docker-compose.yml
  nginx.conf
Labels: ⚙ Setting

#92 publish(#90):마이페이지 인덱스 퍼블리싱 완료
  src/app/api/legends.ts
  src/components/my-page/contents/my-page-index/MyPage.tsx
  src/components/my-page/contents/my-page-index/style.ts
  src/states/userAtoms.ts
  src/types/user.d.ts
Labels: 🎨 Publish

#94 feat(#90):자기소개 클릭시 수정 가능한 기능!
  src/app/api/user.ts
  src/app/my-page/daily-check/page.tsx
  src/components/my-page/contents/daily-check/CheckIn.tsx
  src/components/my-page/contents/daily-check/style.ts
  src/components/my-page/contents/my-page-index/MyPage.tsx
  src/components/my-page/contents/my-page-index/style.ts
  src/components/my-page/user/LeftSection.tsx
  src/states/userAtoms.ts
Labels: ✨ Feature

#97 setting/#67: dockerignore 수정
  .dockerignore
  docker-compose.yml
  nginx.conf
Labels: ⚙ Setting

#96 publish(#95): 출석체크 초안 퍼블리싱 완료
  src/app/api/user.ts
  src/components/my-page/contents/daily-check/CheckIn.tsx
  src/components/my-page/contents/daily-check/DayCheckBox.tsx
  src/components/my-page/contents/daily-check/EmojiKeyboard.tsx
  src/components/my-page/contents/daily-check/style.ts
  src/types/user.d.ts
Labels: 🎨 Publish
