Repository modern-agile-team/ModernWorld-Front, pull requests merged in 2024-08, with the labels that each got.

#102 feat(#95): 출석 완료 처리 기능 하는 중 (오류남)
  .vscode/settings.json
  package-lock.json
  package.json
  src/app/api/sse/PostEvent.js
  src/app/api/sse/eventsource.js
  src/app/api/user.ts
  src/app/layout.tsx
  src/app/test/page.tsx
  src/components/index-page/Loading.tsx
  src/components/index-page/LoginPage.tsx
  src/components/my-page/contents/daily-check/CheckIn.tsx
  src/components/my-page/contents/daily-check/DayCheckBox.tsx
  src/components/my-page/contents/daily-check/EmojiKeyboard.tsx
  src/components/my-page/contents/daily-check/style.ts
  src/components/my-page/contents/inventory/InventoryItemBox.tsx
  src/components/my-page/user/LeftSection.tsx
  src/components/notification/notification.tsx
  src/components/notification/style.ts
  src/components/notification/styled.ts
  src/states/alarmStore/alarm.ts
  src/states/alarmStore/alarmStore.ts
  src/states/userAtoms.ts
  src/types/style.d.ts
  src/utils/daysConstants.ts
  src/utils/emojiConstants.ts
  tsconfig.json
Labels: ✨ Feature

#109 refactor/#67: gitignore server.js 추가
  .gitignore
Labels: 🐞 BugFix

#113 setting/#67: package.json 수정
  package.json
Labels: ⚙ Setting

#114 setting/#67: package.json 수정
  package.json
Labels: ⚙ Setting

#108 이웃 페이지 퍼블리싱 완료했습니다!
  src/app/my-page/neighbor/page.tsx
  src/components/my-page/contents/my-page-index/MyPage.tsx
  src/components/my-page/contents/neighbor/List.tsx
  src/components/my-page/contents/neighbor/Management.tsx
  src/components/my-page/contents/neighbor/Neighbor.tsx
  src/components/my-page/contents/neighbor/NeighborBody.tsx
  src/components/my-page/contents/neighbor/Pagination.tsx
  src/components/my-page/contents/neighbor/SideBookMark.tsx
  src/components/my-page/contents/neighbor/UserListItem.tsx
  src/components/my-page/contents/neighbor/style.ts
  src/components/my-page/user/Category.tsx
  src/states/neighbor.ts
  src/types/style.d.ts
Labels: 🎨 Publish

#116 feat(#103):이웃 관련 API
  .gitignore
  src/app/api/neighbor.ts
Labels: ✨ Feature

#120 feat(#103): 데이터 불러오기 + 친구 수락/거절 기능
  .vscode/settings.json
  package-lock.json
  package.json
  src/app/api/neighbor.ts
  src/app/api/user.ts
  src/components/my-page/contents/my-page-index/MyPage.tsx
  src/components/my-page/contents/neighbor/List.tsx
  src/components/my-page/contents/neighbor/Management.tsx
  src/components/my-page/contents/neighbor/Neighbor.tsx
  src/components/my-page/contents/neighbor/NeighborBody.tsx
  src/components/my-page/contents/neighbor/Pagination.tsx
  src/components/my-page/contents/neighbor/SearchBar.tsx
  src/components/my-page/contents/neighbor/SideBookMark.tsx
  src/components/my-page/contents/neighbor/UserListItem.tsx
  src/components/my-page/contents/neighbor/style.ts
  src/states/neighbor.ts
  src/types/neighbors.d.ts
  src/types/user.d.ts
Labels: ✨ Feature

#124 우편함 페이지에서 답장&다시 보내기 모달창 구현하였습니다
  my-loader.ts
  next.config.js
  src/app/api/neighbor.ts
  src/app/my-page/mailbox/page.tsx
  src/app/my-page/neighbor/page.tsx
  src/components/my-page/contents/mail-box/PostInfo.tsx
  src/components/my-page/contents/mail-box/style.ts
  src/components/my-page/contents/neighbor/UserListItem.tsx
  src/components/my-page/send-post-modal/SendPostModal.tsx
  src/components/my-page/send-post-modal/style.ts
  src/states/mailboxAtoms.ts
  src/states/neighbor.ts
  src/types/mailBox.d.ts
  src/types/style.d.ts
Labels: ✨ Feature

#126 feat(#125):업적, 서비스정보페이지이동과 틀 정도만 잡아둔 상태
  src/app/my-page/achievement-settings/page.tsx
  src/app/my-page/service-info/page.tsx
  src/components/my-page/contents/my-page-index/AchievementSettings.tsx
  src/components/my-page/contents/my-page-index/MyPage.tsx
  src/components/my-page/contents/my-page-index/ServiceInfo.tsx
  src/components/my-page/contents/my-page-index/style.ts
  src/components/my-page/send-post-modal/SendPostModal.tsx
Labels: ✨ Feature

#128 publish(#125): 업적 페이지 퍼블리싱
  .github/ISSUE_TEMPLATE/new-issue---.md
  README.md
  src/app/api/user.ts
  src/app/lib/registry.tsx
  src/app/my-page/inventory/page.tsx
  src/app/my-page/layout.tsx
  src/app/shop/layout.tsx
  src/app/shop/page.tsx
  src/components/my-page/contents/inventory/Inventory.tsx
  src/components/my-page/contents/inventory/InventoryBody.tsx
  src/components/my-page/contents/my-page-index/AchievementEle.tsx
  src/components/my-page/contents/my-page-index/AchievementSettings.tsx
  src/components/my-page/contents/my-page-index/MyPage.tsx
  src/components/my-page/contents/my-page-index/ServiceInfo.tsx
  src/components/my-page/contents/my-page-index/style.ts
  src/components/shop-page/Shop.tsx
  src/components/shop-page/ShopBody.tsx
  src/style/globals.css
  src/types/utils.d.ts
  src/utils/achievements.ts
  src/utils/serviceInfo.ts
  tailwind.config.ts
Labels: 🎨 Publish

#139 feat(#100):event-source-polyfill을 이용하여 headers에 토큰 실어서 보냄
  package-lock.json
  package.json
  src/components/game-page/rockscissorspaper-page/MiddleSection.tsx
  src/components/game-page/rockscissorspaper-page/UserSection.tsx
  src/components/notification/NotificationComponent.tsx
Labels: ✨ Feature

#138 Feature/comment/#134
  src/app/api/axiosInstance.ts
  src/app/api/comment.ts
  src/app/previewVillageUsers/[userId]/comment/page.tsx
  src/app/previewVillageUsers/[userId]/page.tsx
  src/components/village-page/comment/Comment.tsx
  src/components/village-page/comment/PostComment.tsx
  src/components/village-page/comment/RedirectPrevPage.tsx
  src/components/village-page/comment/ShowCommenetList.tsx
  src/components/village-page/comment/UserName.tsx
  src/components/village-page/comment/UserRoom.tsx
  src/components/village-page/comment/styled.ts
  src/components/village-page/preview/previewVillageUsers.tsx
  src/states/commentRefresh.ts
  src/states/village.ts
Labels: ✨ Feature

#136 feat(#129):프로필 사진 업데이트 기능 구현
  src/app/api/user.ts
  src/components/my-page/contents/my-page-index/MyPage.tsx
Labels: ✨ Feature

#141 업적 페이지 기능 추가 및 적용 완료
  src/app/api/achievement.ts
  src/app/api/user.ts
  src/components/my-page/contents/my-page-index/AchievementSettings.tsx
  src/components/my-page/contents/my-page-index/MyPage.tsx
  src/components/my-page/contents/my-page-index/style.ts
  src/components/my-page/user/CharacterInfo.tsx
  src/components/my-page/user/LeftSection.tsx
  src/components/my-page/user/style.ts
  src/states/userAtoms.ts
  src/types/achievement.d.ts
  src/utils/achievements.ts
Labels: ✨ Feature

#144 bugfix(#142): 상점 오류 수정
  src/components/shop-page/ItemClick.tsx
Labels: 🐞 BugFix

#145 Feature/error/#140
  .gitignore
  launch.json
  src/app/api/comment.ts
  src/app/api/game.ts
  src/app/api/getToken.ts
  src/app/api/neighbor.ts
  src/app/api/user.ts
  src/app/error.js
  src/app/layout.tsx
  src/app/loading.tsx
  src/app/loginpage/page.tsx
  src/app/mainpage/page.tsx
  src/app/not-found.tsx
  src/app/not-found/page.tsx
  src/app/page.tsx
  src/app/previewVillageUsers/[userId]/page.tsx
  src/components/error-page/Not_found.tsx
  src/components/error-page/styled.ts
  src/components/index-page/Loading.tsx
  src/components/index-page/LoginPage.tsx
  src/components/index-page/MainPage.tsx
  src/components/index-page/NewUser.tsx
  src/components/index-page/NewUserCreateNickname.tsx
  src/components/index-page/style.ts
  src/components/village-page/preview/previewVillageUsers.tsx
  src/types/error.d.ts
  src/utils/httpStatusCode.ts
  tsconfig.json
Labels: ✨ Feature, 🐞 BugFix

#151 refactor/#67: docker compose 오타 및 dockerfile 수정으로 이미지 용량 줄이기
  docker-compose.yml
  dockerfile
  next.config.js
Labels: 🔨 Refactor

#152 refactor/#67: 오타 수정
  dockerfile
Labels: 🔨 Refactor

#153 Feature/comment/#134
  src/app/api/comment.ts
  src/components/village-page/comment/ShowCommenetList.tsx
  src/components/village-page/comment/styled.ts
Labels: ✨ Feature

#146 펫 룸 만들었습니다 추가로 메일함에서 갑자기 오류가 나서 수정했습니다.
  src/app/api/inventory.ts
  src/app/my-page/pet-room/page.tsx
  src/components/my-page/contents/mail-box/ItemListEle.tsx
  src/components/my-page/contents/mail-box/MailBoxBodyEle.tsx
  src/components/my-page/contents/mail-box/Title.tsx
  src/components/my-page/contents/my-pet-room/MyPetRoom.tsx
  src/components/my-page/contents/my-pet-room/style.ts
  src/components/my-page/user/Category.tsx
  src/types/mailBox.d.ts
Labels: ✨ Feature, 🐞 BugFix

#149 Publish/village2/#8
  src/app/village/dog/page.tsx
  src/app/village/page.tsx
  src/components/village-page/Default.tsx
  src/components/village-page/Pagenation.tsx
  src/components/village-page/SearchBox.tsx
  src/components/village-page/SortDiv.tsx
  src/components/village-page/Village.tsx
  src/components/village-page/getUserApi.tsx
  src/components/village-page/preview/previewVillageUsers.tsx
  src/components/village-page/styled.ts
  src/states/village.ts
  src/utils/image.ts
Labels: 🎨 Publish

#155 Feature/reply/#154
  src/app/api/reply.ts
  src/app/layout.tsx
  src/app/previewVillageUsers/[userId]/comment/page.tsx
  src/components/village-page/comment/PostComment.tsx
  src/components/village-page/comment/ShowCommenetList.tsx
  src/components/village-page/comment/reply/PostReply.tsx
  src/components/village-page/comment/reply/Reply.tsx
  src/components/village-page/comment/reply/ReplyModalBody.tsx
  src/components/village-page/comment/reply/ReplyModalHeader.tsx
  src/components/village-page/comment/reply/styled.ts
  src/components/village-page/comment/styled.ts
  src/components/village-page/preview/previewVillageUsers.tsx
  src/states/reply.ts
Labels: ✨ Feature

#150 마이페이지 인덱스 메뉴 모달창 로그아웃창 퍼블리싱 완료
  src/app/api/Alarms.ts
  src/components/my-page/contents/menu/AlarmList.tsx
  src/components/my-page/contents/menu/AlarmModal.tsx
  src/components/my-page/contents/menu/LogoutModal.tsx
  src/components/my-page/contents/menu/MenuModal.tsx
  src/components/my-page/contents/menu/style.ts
  src/components/my-page/contents/my-page-index/MyPage.tsx
  src/states/userAtoms.ts
  src/types/alarm.d.ts
  src/types/style.d.ts
Labels: ✨ Feature, 🎨 Publish

#156 next.config.js 파일 수정
  next.config.js
Labels: 🔨 Refactor

#158 중복된 부분 수정
  src/components/village-page/preview/previewVillageUsers.tsx
Labels: 🔨 Refactor

#159 refactor/#67: dockerfile 처음으로 수정
  dockerfile
Labels: 🔨 Refactor

#162 Publish/preview village users/(#15)
  src/app/api/legends.ts
  src/app/previewVillageUsers/[userId]/page.tsx
  src/components/my-room/style.ts
  src/components/village-page/preview/modal/GetHeartLegendModal.tsx
  src/components/village-page/preview/modal/styled.ts
  src/components/village-page/preview/previewVillageUsers.tsx
  src/states/village.ts
  src/types/legend.d.ts
Labels: ✨ Feature, 🎨 Publish

#163 좋아요 모달창 퍼블리싱만 완료했습니다.
  .vscode/settings.json
  src/app/api/legends.ts
  src/components/my-page/contents/my-page-index-modal/AlarmList.tsx
  src/components/my-page/contents/my-page-index-modal/AlarmModal.tsx
  src/components/my-page/contents/my-page-index-modal/LogoutModal.tsx
  src/components/my-page/contents/my-page-index-modal/style.ts
  src/components/my-page/contents/my-page-index/LikeModal.tsx
  src/components/my-page/contents/my-page-index/MenuModal.tsx
  src/components/my-page/contents/my-page-index/MyPage.tsx
  src/components/my-page/user/Category.tsx
  src/states/userAtoms.ts
  src/types/legend.d.ts
  src/types/style.d.ts
  src/types/user.d.ts
Labels: 🎨 Publish

#166 Setting/프론트 서버와 cicd 구현/#67
  dockerfile
Labels: 🔨 Refactor, ✅ Test

#168 modify(#160):좋아요 모달 방 보러가기 오류 수정
  src/components/my-page/contents/my-page-index-modal/LogoutModal.tsx
  src/components/my-page/contents/my-page-index-modal/style.ts
  src/components/my-page/contents/my-page-index/LikeModal.tsx
Labels: 📝 Modify

#171 Bugfix/all/#167
  next.config.js
  src/app/api/game.ts
  src/app/previewVillageUsers/[userId]/comment/page.tsx
  src/app/previewVillageUsers/[userId]/page.tsx
  src/components/game-page/rockscissorspaper-page/MiddleSection.tsx
  src/components/game-page/rockscissorspaper-page/RecordComponent.tsx
  src/components/village-page/Default.tsx
  src/components/village-page/Pagenation.tsx
  src/components/village-page/SearchBox.tsx
  src/components/village-page/SortDiv.tsx
  src/components/village-page/Village.tsx
  src/components/village-page/comment/Comment.tsx
  src/components/village-page/comment/RedirectPrevPage.tsx
  src/components/village-page/comment/ShowCommenetList.tsx
  src/components/village-page/comment/UserName.tsx
  src/components/village-page/comment/UserRoom.tsx
  src/components/village-page/getUserApi.tsx
  src/components/village-page/preview/modal/GetHeartLegendModal.tsx
  src/components/village-page/preview/modal/GetUsersNickname.tsx
  src/components/village-page/preview/modal/styled.ts
  src/components/village-page/preview/previewVillageUsers.tsx
  src/components/village-page/styled.ts
  src/states/gameAtom.ts
  src/types/game.d.ts
  src/utils/color.ts
  tsconfig.json
Labels: 🔨 Refactor, 🐞 BugFix

#173 Refoctor/preview village users/#172
  my-loader.ts
  src/app/loading.tsx
  src/app/previewVillageUsers/[userId]/page.tsx
  src/components/village-page/Pagenation.tsx
  src/components/village-page/SearchBox.tsx
  src/components/village-page/Village.tsx
  src/components/village-page/comment/reply/ReplyModalBody.tsx
  src/components/village-page/comment/reply/ReplyModalHeader.tsx
  src/components/village-page/getUserApi.tsx
  src/components/village-page/preview/AddFriend.tsx
  src/components/village-page/preview/ExitButton.tsx
  src/components/village-page/preview/GetUserCommentCount.tsx
  src/components/village-page/preview/LikeComponent.tsx
  src/components/village-page/preview/modal/GetHeartLegendModal.tsx
  src/components/village-page/preview/modal/GetUsersNickname.tsx
  src/components/village-page/preview/previewVillageUsers.tsx
  src/components/village-page/preview/style.ts
  src/states/village.ts
  src/utils/image.ts
Labels: 🔨 Refactor

#174 Refactor/comment/#172
  src/components/index-page/Loading.tsx
  src/components/village-page/comment/PostComment.tsx
  src/components/village-page/comment/RedirectPrevPage.tsx
  src/components/village-page/comment/ShowCommenetList.tsx
  src/components/village-page/comment/styled.ts
  src/utils/image.ts
Labels: 🔨 Refactor

#177 bugfix(#167): localstorage is not defined && ldrs 제거
  next.config.js
  package-lock.json
  package.json
  src/app/api/user.ts
  src/app/loading.tsx
  src/components/game-page/rockscissorspaper-page/BotSection.tsx
  src/components/game-page/rockscissorspaper-page/MiddleSection.tsx
  src/components/game-page/rockscissorspaper-page/RecordComponent.tsx
  src/components/index-page/Loading.tsx
  src/components/index-page/LoginPage.tsx
  src/components/index-page/MainPage.tsx
  src/components/index-page/NewUserCreateNickname.tsx
  src/components/index-page/style.ts
  src/components/my-page/contents/daily-check/CheckIn.tsx
  src/components/my-page/contents/inventory/InventoryItemBox.tsx
  src/components/my-page/contents/my-page-index/LikeModal.tsx
  src/components/my-page/contents/my-pet-room/MyPetRoom.tsx
  src/components/my-page/contents/neighbor/List.tsx
  src/components/my-page/contents/neighbor/SearchBar.tsx
  src/components/my-page/user/LeftSection.tsx
  src/components/my-room/Area7_8_9.tsx
  src/components/my-room/GetUserCharacter.tsx
  src/components/my-room/style.ts
  src/components/notification/style.ts
  src/types/style.d.ts
  src/utils/getUserNo.ts
  src/utils/image.ts
Labels: 🐞 BugFix

#176 feat(#170): 여러 기능 추가 & 수정
  src/app/api/logout.ts
  src/components/my-page/contents/mail-box/ItemList.tsx
  src/components/my-page/contents/mail-box/PostInfo.tsx
  src/components/my-page/contents/mail-box/PresentInfo.tsx
  src/components/my-page/contents/my-page-index-modal/AlarmList.tsx
  src/components/my-page/contents/my-page-index-modal/AlarmModal.tsx
  src/components/my-page/contents/my-page-index-modal/LogoutModal.tsx
  src/components/my-page/contents/my-page-index/LikeModal.tsx
  src/components/my-page/contents/neighbor/UserListItem.tsx
  src/components/shop-page/ShopItemBox.tsx
  src/utils/date.ts
  src/utils/errorCode.ts
Labels: 🔨 Refactor, ✨ Feature, 📝 Modify

#181 dockerfile 수정
  dockerfile
Labels: 🔨 Refactor

#185 dockerfile 수정
  dockerfile
Labels: 🔨 Refactor

#186 dockerfile 수정
  dockerfile
Labels: 🔨 Refactor

#187 dockerfile 수정
  dockerfile
  package.json
Labels: 🔨 Refactor

#188 dockerfile env 부분 수정
  dockerfile
  package.json
Labels: 🔨 Refactor

#189 dockerfile 수정
  dockerfile
Labels: 🔨 Refactor

#179 feat(#170):회원 탈퇴 구현 완료
  src/app/api/auth.ts
  src/app/api/logout.ts
  src/components/my-page/contents/mail-box/ItemList.tsx
  src/components/my-page/contents/mail-box/ItemListEle.tsx
  src/components/my-page/contents/mail-box/PostInfo.tsx
  src/components/my-page/contents/mail-box/PresentInfo.tsx
  src/components/my-page/contents/mail-box/Title.tsx
  src/components/my-page/contents/mail-box/style.ts
  src/components/my-page/contents/my-page-index-modal/AlarmList.tsx
  src/components/my-page/contents/my-page-index-modal/AlarmModal.tsx
  src/components/my-page/contents/my-page-index-modal/LogoutModal.tsx
  src/components/my-page/contents/my-page-index/MenuModal.tsx
  src/components/my-page/contents/my-page-index/ServiceInfo.tsx
  src/components/my-page/contents/neighbor/List.tsx
  src/components/my-page/contents/neighbor/SearchBar.tsx
  src/components/my-page/pagination/Pagination.tsx
  src/components/my-page/user/CharacterInfo.tsx
  src/types/style.d.ts
  src/utils/image.ts
  src/utils/serviceInfo.ts
Labels: ✨ Feature

#184 Refactor/index/#172
  src/app/api/axiosInstance.ts
  src/app/api/getToken.ts
  src/app/layout.tsx
  src/components/index-page/Loading.tsx
  src/components/index-page/LoginPage.tsx
  src/components/index-page/MainPage.tsx
  src/components/index-page/NewUser.tsx
  src/components/index-page/NewUserCreateNickname.tsx
  src/components/index-page/NewUserSelectFirstCharacter.tsx
  src/components/index-page/style.ts
  src/components/notification/NotificationComponent.tsx
  src/components/village-page/Default.tsx
  src/states/authAtom.ts
  src/utils/image.ts
Labels: 🔨 Refactor

#190 env 부분 전면 수정
  .github/workflows/git-action.yml
  dockerfile
Labels: 🔨 Refactor

#191 git-action.ymal 수정
  .github/workflows/git-action.yml
Labels: 🔨 Refactor

#192 env를 읽기 위한 과정1
  dockerfile
Labels: ✅ Test

#193 front server를 위한 수정
  .github/workflows/git-action.yml
  dockerfile
Labels: 🔨 Refactor

#195 dockerfile 전면 수정
  dockerfile
Labels: ✅ Test

#197 dockerignore 수정
  .dockerignore
  dockerfile
Labels: ✅ Test

#198 sharp install
  package-lock.json
  package.json
Labels: ✅ Test

#199 서버 오류를 잡기 위한 next.config 수정
  next.config.js
Labels: ✅ Test

#201 image에 env를 넣지 않기 위한 작업입니다.
  .dockerignore
  docker-compose.yml
Labels: ✅ Test

#200 Refactor/game/#172
  package-lock.json
  package.json
  src/app/api/game.ts
  src/components/game-page/Lobby.tsx
  src/components/game-page/rockscissorspaper-page/BotSection.tsx
  src/components/game-page/rockscissorspaper-page/MiddleSection.tsx
  src/components/game-page/rockscissorspaper-page/OnlyRecord.tsx
  src/components/game-page/rockscissorspaper-page/RecordComponent.tsx
  src/components/game-page/rockscissorspaper-page/TimerIfYouWantPlay.tsx
  src/components/game-page/rockscissorspaper-page/UserSection.tsx
  src/components/game-page/styled.ts
  src/components/notification/NotificationComponent.tsx
  src/components/village-page/comment/Comment.tsx
  src/components/village-page/comment/PostComment.tsx
  src/components/village-page/preview/ExitButton.tsx
  src/states/gameAtom.ts
  src/types/style.d.ts
  src/utils/date.ts
  src/utils/image.ts
  src/utils/rockScissorsPaper.ts
Labels: 🔨 Refactor, ❌ Delete, 🐞 BugFix

#202 dockerignore 수정
  .dockerignore
  docker-compose.yml
Labels: ✅ Test

#194 Refactor/all jin page/#170
  src/app/api/inventory.ts
  src/app/api/shop.ts
  src/components/my-page/contents/daily-check/CheckIn.tsx
  src/components/my-page/contents/mail-box/PostInfo.tsx
  src/components/my-page/contents/mail-box/SideBookMark.tsx
  src/components/my-page/contents/my-page-index-modal/AlarmList.tsx
  src/components/my-page/contents/my-page-index/AchievementEle.tsx
  src/components/my-page/contents/my-page-index/AchievementSettings.tsx
  src/components/my-page/contents/my-page-index/style.ts
  src/components/my-page/pagination/Pagination.tsx
  src/components/my-page/send-post-modal/SendPostModal.tsx
  src/components/my-page/user/LeftSection.tsx
  src/components/shop-page/ItemClickModal.tsx
  src/states/userAtoms.ts
  src/types/utils.d.ts
  src/utils/achievements.ts
  src/utils/errorCode.ts
  src/utils/image.ts
  src/utils/serviceInfo.ts
Labels: 📝 Modify

#203 dockerfile 수정
  dockerfile
Labels: ✅ Test

#204 서버에서 발생하는 오류를 잡기 위해 next.config 파일 수정
  next.config.js
Labels: 🔨 Refactor

#205 Refactor/comment/#172
  src/app/api/getToken.ts
  src/components/village-page/Default.tsx
  src/components/village-page/Village.tsx
  src/components/village-page/comment/PostComment.tsx
  src/components/village-page/comment/ShowCommenetList.tsx
  src/components/village-page/comment/reply/PostReply.tsx
  src/components/village-page/comment/reply/Reply.tsx
  src/components/village-page/comment/reply/ReplyModalBody.tsx
  src/components/village-page/comment/reply/ReplyModalHeader.tsx
  src/components/village-page/comment/reply/styled.ts
  src/components/village-page/comment/styled.ts
  src/components/village-page/styled.ts
  src/types/style.d.ts
Labels: ✨ Feature

#206 next.config.js header 부분 수정
  next.config.js
Labels: 🔨 Refactor

#207 서버를 위한 next.config.js 수정
  next.config.js
Labels: 🔨 Refactor

#208 next.config.js 수정
  next.config.js
  nginx.conf
Labels: 🔨 Refactor
