Repository modern-agile-team/ModernWorld-Front, pull requests merged in 2024-05, with the labels that each got.

#7 publish(#4) : 캐릭터 생성 페이지 퍼블리싱 1차 완성본
  src/app/createcharacter/page.tsx
  src/app/login/page.tsx
  src/app/main/page.tsx
  src/app/newcharacter/page.tsx
  src/app/page.tsx
  src/components/index-page/BackgroundColor.ts
  src/components/index-page/InputNickname.ts
  src/components/index-page/LoginBtn.tsx
  src/components/index-page/LoginPage.tsx
  src/components/index-page/MainLogo.ts
  src/components/index-page/MainLogoText.ts
  src/components/index-page/MainPage.tsx
  src/components/index-page/MainPowerBtn.ts
  src/components/index-page/NewCharacter.tsx
  src/components/index-page/NewCharacterHook.tsx
  src/components/index-page/NewNicknameCondition.tsx
  src/components/index-page/style.ts
Labels: Publish

#9 publish(#5): 마이페이지 left section 완성 컴포넌트로 쪼개는 작업 시작
  src/app/my-page/layout.tsx
  src/app/my-page/page.tsx
  src/components/my-page/style.ts
  src/components/my-page/test
  src/components/my-page/user/Category.tsx
  src/components/my-page/user/CharacterInfo.tsx
  src/components/my-page/user/LeftSection.tsx
  src/components/my-page/user/PointInfo.tsx
  src/style/globals.css
Labels: Publish

#10 Modify/layout/#2
  .github/pull_request_templete.md
  package-lock.json
  package.json
  src/app/api/mock.ts
  src/app/village/page.tsx
  src/components/index-page/LoginBtn.tsx
  src/components/index-page/LoginPage.tsx
  src/components/index-page/NewCharacter.tsx
  src/components/index-page/NewCharacterHook.tsx
  src/components/index-page/NewNicknameCondition.tsx
  src/components/index-page/style.ts
  src/components/village-page/Village.tsx
  src/components/village-page/style.ts
Labels: Modify

#12 publish(#5) : 인벤토리 우편함 컴포넌트 나누고 우편함 퍼블리싱 거의 완성
  src/app/my-page/inventory/page.tsx
  src/app/my-page/mailbox/page.tsx
  src/components/my-page/contents/inventory/InvenRightBookMark.tsx
  src/components/my-page/contents/inventory/Inventory.tsx
  src/components/my-page/contents/inventory/InventoryBody.tsx
  src/components/my-page/contents/inventory/InventoryHeader.tsx
  src/components/my-page/contents/inventory/InventoryItemBox.tsx
  src/components/my-page/contents/inventory/style.ts
  src/components/my-page/contents/mail-box/GiftTitle.tsx
  src/components/my-page/contents/mail-box/ItemInfo.tsx
  src/components/my-page/contents/mail-box/ItemList.tsx
  src/components/my-page/contents/mail-box/ItemListEle.tsx
  src/components/my-page/contents/mail-box/MailBox.tsx
  src/components/my-page/contents/mail-box/MailBoxBody.tsx
  src/components/my-page/contents/mail-box/MailBoxBodyEle.tsx
  src/components/my-page/contents/mail-box/style.ts
  src/components/my-page/contents/style.ts
  src/components/my-page/pagination/Pagination.tsx
  src/components/my-page/pagination/style.ts
  src/components/my-page/user/Category.tsx
Labels: Publish

#13 Publish(#8) : 마을 정렬 기능 구현 중간 PR
  src/app/village/page.tsx
  src/components/index-page/LoginPage.tsx
  src/components/index-page/style.ts
  src/components/village-page/RadioSort.tsx
  src/components/village-page/Village.tsx
  src/components/village-page/VillageDog.tsx
  src/components/village-page/getUserApi.tsx
  src/components/village-page/style.ts
Labels: Modify

#16 feature(#14) : 기능 추가 (Link, path)
  src/app/my-page/page.tsx
  src/app/shop/layout.tsx
  src/app/shop/page.tsx
  src/app/test/page.tsx
  src/components/my-page/contents/mail-box/style.ts
  src/components/my-page/user/Category.tsx
  src/components/my-page/user/style.ts
  src/untils/test
  src/utils/DataDisplay.tsx
  src/utils/useFetchData.ts
Labels: Feature

#21 feature(#14) : axsios 이용하여 인벤토리에 데이터 불러옴 (라벨 구현 시작)
  src/app/test/page.tsx
  src/components/my-page/contents/inventory/InvenRightBookMark.tsx
  src/components/my-page/contents/inventory/InventoryHeader.tsx
  src/components/my-page/contents/inventory/InventoryItemBox.tsx
  src/components/my-page/contents/inventory/style.ts
  src/hooks/GetInventoryList.tsx
  src/utils/DataDisplay.tsx
  src/utils/useFetchData.ts
  src/utils/useGetData.ts
Labels: Feature
