Repository modern-agile-team/ModernWorld-Front, pull requests merged in 2024-09, with the labels that each got.

#210 도메인 수정 했습니다.
  docker-compose.yml
  next.config.js
  nginx.conf
Labels: 🌏 Deploy

#211 추가적인 부분 수정입니다.
  dockerfile
  nginx.conf
Labels: 🌏 Deploy

#212 next.config.js 불필요한 부분 수정
  dockerfile
  next.config.js
Labels: 🌏 Deploy

#209 myroom리팩토링
  src/app/api/getToken.ts
  src/app/loading.tsx
  src/app/my-page/layout.tsx
  src/components/index-page/MainPage.tsx
  src/components/my-page/contents/my-page-index-modal/AlarmModal.tsx
  src/components/my-page/contents/my-page-index/MyPage.tsx
  src/components/my-page/contents/my-page-index/style.ts
  src/components/my-page/contents/my-pet-room/MyPetRoom.tsx
  src/components/my-page/contents/neighbor/Pagination.tsx
  src/components/my-page/pagination/Pagination.tsx
  src/components/my-page/user/style.ts
  src/components/my-room/Area1_4_5.tsx
  src/components/my-room/Area7_8_9.tsx
  src/components/my-room/GetUserCharacter.tsx
  src/components/my-room/MyRoom.tsx
  src/components/my-room/style.ts
  src/components/shop-page/ItemClickModal.tsx
  src/components/village-page/preview/LikeComponent.tsx
  src/states/userAtoms.ts
  src/types/style.d.ts
  src/types/user.d.ts
  src/utils/image.ts
  src/utils/itemSizeConstains.ts
Labels: 🔨 Refactor, 🐞 BugFix

#217 modify(#170): 친구신청 UI 변경
  src/app/api/user.ts
  src/components/my-page/contents/inventory/style.ts
  src/components/my-page/contents/neighbor/SearchBar.tsx
  src/components/my-page/contents/neighbor/style.ts
  src/components/my-page/user/CharacterInfo.tsx
Labels: 📝 Modify

#220 출석체크 버그수정
  src/components/my-page/contents/daily-check/CheckIn.tsx
  src/components/my-page/contents/my-page-index/ServiceInfo.tsx
  src/components/shop-page/ItemClickModal.tsx
  src/utils/daysConstants.ts
  src/utils/errorCode.ts
  src/utils/serviceInfo.ts
Labels: 🐞 BugFix

#219 Refactor/my room/#172
  public/fonts/neodgm.ttf
  src/app/globalStyles.tsx
  src/app/layout.tsx
  src/components/my-page/contents/my-page-index/MyPage.tsx
  src/components/my-page/contents/my-page-index/style.ts
  src/components/my-room/Area1_4_5.tsx
  src/components/my-room/Area7_8_9.tsx
  src/components/my-room/MyRoom.tsx
  src/components/my-room/style.ts
  src/components/my-room/useCheckItemSizeHook.ts
  src/components/village-page/comment/Comment.tsx
  src/components/village-page/comment/UserRoom.tsx
  src/components/village-page/comment/styled.ts
  src/components/village-page/getUserApi.tsx
  src/components/village-page/preview/LikeComponent.tsx
  src/components/village-page/preview/previewVillageUsers.tsx
  src/components/village-page/styled.ts
  src/types/village.d.ts
  src/utils/itemSizeConstains.ts
Labels: 🔨 Refactor, 🐞 BugFix

#221 bugfix(#172):위치 조정이랑 폰트 적용2트
  src/app/layout.tsx
  src/components/my-room/MyRoom.tsx
  src/utils/itemSizeConstains.ts
Labels: 🐞 BugFix

#226 server action 오류를 해결하기 위해 next.config.js 수정
  next.config.js
Labels: ✅ Test

#228 bugfix(#172):완
  src/app/api/axiosInstance.ts
  src/app/api/inventory.ts
  src/components/index-page/NewUserCreateNickname.tsx
  src/components/my-room/GetUserCharacter.tsx
  src/components/my-room/MyRoom.tsx
  src/components/my-room/style.ts
  src/utils/image.ts
  src/utils/itemSizeConstains.ts
Labels: 🐞 BugFix

#227 feat(#170): 상점 고치고 이용약관 만들기
  src/app/my-page/layout.tsx
  src/app/shop/layout.tsx
  src/app/terms-of-service/page.tsx
  src/components/my-page/contents/inventory/style.ts
  src/components/my-page/contents/my-page-index/style.ts
  src/components/my-page/user/style.ts
  src/components/shop-page/ItemClickModal.tsx
  src/components/shop-page/ShopItemBox.tsx
  src/components/shop-page/style.ts
Labels: ✨ Feature

#230 refactor/#67: next.config.js 필요없는 부분 삭제
  next.config.js
Labels: 🔨 Refactor

#232 modify(#170): 기타 오류 수정
  src/app/api/mailBox.ts
  src/components/shop-page/ItemClickModal.tsx
  src/components/shop-page/style.ts
Labels: 📝 Modify
